version: '3.1'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3001:3306"
    volumes:
      - ../db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      net:
        ipv4_address: 172.16.1.3
  grafana-service:
    image: grafana/grafana
    restart: always
    depends_on:
      - db
    ports:
      - "3002:3000"
    volumes:
      - ../grafana_data:/var/lib/grafana
    networks:
      net:
        ipv4_address: 172.16.1.4
networks:
  net:
    external: true
