version: '3.4'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3001:3306"
    volumes:
      - ./drop_database.sql:/docker-entrypoint-initdb.d/drop_database.sql
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
  backup:
    image: mysql:8.0
    volumes:
      - ./backup.sh:/backup.sh
      - ../backup_data:/backup
    command: [ "sh", "/backup.sh" ]
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on: [db]
  restore:
    image: mysql:8.0
    volumes:
      - ./restore.sh:/restore.sh
      - ../backup_data:/backup
    command: [ "sh", "/restore.sh" ]
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dockerlocal
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_PORT: ${DB_PORT}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    env_file:
      - .env
    volumes:
      - ../backup_data:/backup
networks:
  bibliotech:
    external: true
