apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s-service
spec:
  selector:
    app: bibliotech-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer