spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


token:
  signing:
    key: ${JWT_KEY}
  expiration:
    time: ${TOKEN_EXPIRATION_TIME}

superadmin:
  firstname: ${SUPERADMIN_FIRSTNAME}
  lastname: ${SUPERADMIN_LASTNAME}
  password: ${SUPERADMIN_PASSWORD}
  email: ${SUPERADMIN_EMAIL}
