application:
  security:
    jwt:
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
spring:
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
token:
  signing:
    key: ${JWT_KEY}
  expiration:
    time: ${TOKEN_EXPIRATION_TIME}

superadmin:
  firstname: ${SUPERADMIN_FIRSTNAME}
  lastname: ${SUPERADMIN_LASTNAME}
  password: ${SUPERADMIN_PASSWORD}
  email: ${SUPERADMIN_EMAIL}
