logging:
  level:
    org.hibernate.SQL: DEBUG
    com.bibliotech: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

token:
  signing:
    key: test1352675ghjt7789798578455855seserewgweew

