logging:
  level:
    org.hibernate.SQL: DEBUG
    com.bibliotech: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console

token:
  signing:
    key: test1352675ghjt7789798578455855seserewgweew
  expiration:
    time: 5000


application:
  security:
    jwt:
      refresh-token:
        expiration: 604800000

superadmin:
  firstname: ${SUPERADMIN_FIRSTNAME}
  lastname: ${SUPERADMIN_LASTNAME}
  password: ${SUPERADMIN_PASSWORD}
  email: ${SUPERADMIN_EMAIL}
