package com.bibliotech.utils;

public enum ResourceNames {
    AUTOR,
    BIBLIOTECA,
    CARRERA,
    CATEGORIA,
    CATEGORIA_VALOR,
    COMENTARIO,
    EDICION,
    EDITORIAL,
    EJEMPLAR,
    EJEMPLAR_ESTADO,
    ESTADO_EJEMPLAR,
    EVENTO,
    FACULTAD,
    LINK,
    NOTIFICATION,
    MULTA,
    PLATAFORMA,
    PUBLICACION,
    PRESTAMO,
    PRIVILEGE,
    ROLE,
    TIPO_EVENTO,
    TIPO_CATEGORIA,
    TIPO_PUBLICACION,
    UBICACION,
    USER,
    TIPO_MULTA,
}
