---
name: Java CI
on:
  workflow_dispatch: null
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
    - name: Set up JDK 17
      with:
      distribution: 'temurin'
      java-version: '17'
      cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
